# enable zmk studio for realtime keymap updates
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# enable mouse/scroll HID reports for &msc scroll bindings
CONFIG_ZMK_MOUSE=y

# allow 5-key reset combos
CONFIG_ZMK_COMBO_MAX_KEYS_PER_COMBO=5
